// Code generated by typegen/main.go. DO NOT EDIT.

// 国家列表，包含所有受支持的国家及其国旗
export const countries = [
	{
		name: "阿富汗",
		flag: "🇦🇫",
	},
	{
		name: "奥兰群岛",
		flag: "🇦🇽",
	},
	{
		name: "阿尔巴尼亚",
		flag: "🇦🇱",
	},
	{
		name: "阿尔及利亚",
		flag: "🇩🇿",
	},
	{
		name: "美属萨摩亚",
		flag: "🇦🇸",
	},
	{
		name: "安道尔",
		flag: "🇦🇩",
	},
	{
		name: "安哥拉",
		flag: "🇦🇴",
	},
	{
		name: "安圭拉",
		flag: "🇦🇮",
	},
	{
		name: "南极洲",
		flag: "🇦🇶",
	},
	{
		name: "安提瓜和巴布达",
		flag: "🇦🇬",
	},
	{
		name: "阿根廷",
		flag: "🇦🇷",
	},
	{
		name: "亚美尼亚",
		flag: "🇦🇲",
	},
	{
		name: "阿鲁巴",
		flag: "🇦🇼",
	},
	{
		name: "澳大利亚",
		flag: "🇦🇺",
	},
	{
		name: "奥地利",
		flag: "🇦🇹",
	},
	{
		name: "阿塞拜疆",
		flag: "🇦🇿",
	},
	{
		name: "巴哈马",
		flag: "🇧🇸",
	},
	{
		name: "巴林",
		flag: "🇧🇭",
	},
	{
		name: "孟加拉国",
		flag: "🇧🇩",
	},
	{
		name: "巴巴多斯",
		flag: "🇧🇧",
	},
	{
		name: "白俄罗斯",
		flag: "🇧🇾",
	},
	{
		name: "比利时",
		flag: "🇧🇪",
	},
	{
		name: "伯利兹",
		flag: "🇧🇿",
	},
	{
		name: "贝宁",
		flag: "🇧🇯",
	},
	{
		name: "百慕大",
		flag: "🇧🇲",
	},
	{
		name: "不丹",
		flag: "🇧🇹",
	},
	{
		name: "多民族玻利维亚国",
		flag: "🇧🇴",
	},
	{
		name: "博内尔、圣尤斯特歇斯和萨巴",
		flag: "🇧🇶",
	},
	{
		name: "波斯尼亚和黑塞哥维那",
		flag: "🇧🇦",
	},
	{
		name: "博茨瓦纳",
		flag: "🇧🇼",
	},
	{
		name: "布韦岛",
		flag: "🇧🇻",
	},
	{
		name: "巴西",
		flag: "🇧🇷",
	},
	{
		name: "英属印度洋领地",
		flag: "🇮🇴",
	},
	{
		name: "文莱达鲁萨兰国",
		flag: "🇧🇳",
	},
	{
		name: "保加利亚",
		flag: "🇧🇬",
	},
	{
		name: "布基纳法索",
		flag: "🇧🇫",
	},
	{
		name: "布隆迪",
		flag: "🇧🇮",
	},
	{
		name: "柬埔寨",
		flag: "🇰🇭",
	},
	{
		name: "喀麦隆",
		flag: "🇨🇲",
	},
	{
		name: "加拿大",
		flag: "🇨🇦",
	},
	{
		name: "佛得角",
		flag: "🇨🇻",
	},
	{
		name: "开曼群岛",
		flag: "🇰🇾",
	},
	{
		name: "中非共和国",
		flag: "🇨🇫",
	},
	{
		name: "乍得",
		flag: "🇹🇩",
	},
	{
		name: "智利",
		flag: "🇨🇱",
	},
	{
		name: "中国",
		flag: "🇨🇳",
	},
	{
		name: "圣诞岛",
		flag: "🇨🇽",
	},
	{
		name: "科科斯（基林）群岛",
		flag: "🇨🇨",
	},
	{
		name: "哥伦比亚",
		flag: "🇨🇴",
	},
	{
		name: "科摩罗",
		flag: "🇰🇲",
	},
	{
		name: "刚果",
		flag: "🇨🇬",
	},
	{
		name: "刚果民主共和国",
		flag: "🇨🇩",
	},
	{
		name: "库克群岛",
		flag: "🇨🇰",
	},
	{
		name: "哥斯达黎加",
		flag: "🇨🇷",
	},
	{
		name: "科特迪瓦",
		flag: "🇨🇮",
	},
	{
		name: "克罗地亚",
		flag: "🇭🇷",
	},
	{
		name: "古巴",
		flag: "🇨🇺",
	},
	{
		name: "库拉索",
		flag: "🇨🇼",
	},
	{
		name: "塞浦路斯",
		flag: "🇨🇾",
	},
	{
		name: "捷克共和国",
		flag: "🇨🇿",
	},
	{
		name: "丹麦",
		flag: "🇩🇰",
	},
	{
		name: "吉布提",
		flag: "🇩🇯",
	},
	{
		name: "多米尼克",
		flag: "🇩🇲",
	},
	{
		name: "多米尼加共和国",
		flag: "🇩🇴",
	},
	{
		name: "厄瓜多尔",
		flag: "🇪🇨",
	},
	{
		name: "埃及",
		flag: "🇪🇬",
	},
	{
		name: "萨尔瓦多",
		flag: "🇸🇻",
	},
	{
		name: "赤道几内亚",
		flag: "🇬🇶",
	},
	{
		name: "厄立特里亚",
		flag: "🇪🇷",
	},
	{
		name: "爱沙尼亚",
		flag: "🇪🇪",
	},
	{
		name: "埃塞俄比亚",
		flag: "🇪🇹",
	},
	{
		name: "福克兰群岛（马尔维纳斯）",
		flag: "🇫🇰",
	},
	{
		name: "法罗群岛",
		flag: "🇫🇴",
	},
	{
		name: "斐济",
		flag: "🇫🇯",
	},
	{
		name: "芬兰",
		flag: "🇫🇮",
	},
	{
		name: "法国",
		flag: "🇫🇷",
	},
	{
		name: "法属圭亚那",
		flag: "🇬🇫",
	},
	{
		name: "法属波利尼西亚",
		flag: "🇵🇫",
	},
	{
		name: "法属南部领地",
		flag: "🇹🇫",
	},
	{
		name: "加蓬",
		flag: "🇬🇦",
	},
	{
		name: "冈比亚",
		flag: "🇬🇲",
	},
	{
		name: "格鲁吉亚",
		flag: "🇬🇪",
	},
	{
		name: "德国",
		flag: "🇩🇪",
	},
	{
		name: "加纳",
		flag: "🇬🇭",
	},
	{
		name: "直布罗陀",
		flag: "🇬🇮",
	},
	{
		name: "希腊",
		flag: "🇬🇷",
	},
	{
		name: "格陵兰",
		flag: "🇬🇱",
	},
	{
		name: "格林纳达",
		flag: "🇬🇩",
	},
	{
		name: "瓜德罗普",
		flag: "🇬🇵",
	},
	{
		name: "关岛",
		flag: "🇬🇺",
	},
	{
		name: "危地马拉",
		flag: "🇬🇹",
	},
	{
		name: "根西岛",
		flag: "🇬🇬",
	},
	{
		name: "几内亚",
		flag: "🇬🇳",
	},
	{
		name: "几内亚比绍",
		flag: "🇬🇼",
	},
	{
		name: "圭亚那",
		flag: "🇬🇾",
	},
	{
		name: "海地",
		flag: "🇭🇹",
	},
	{
		name: "赫德岛和麦克唐纳群岛",
		flag: "🇭🇲",
	},
	{
		name: "梵蒂冈",
		flag: "🇻🇦",
	},
	{
		name: "洪都拉斯",
		flag: "🇭🇳",
	},
	{
		name: "香港",
		flag: "🇭🇰",
	},
	{
		name: "匈牙利",
		flag: "🇭🇺",
	},
	{
		name: "冰岛",
		flag: "🇮🇸",
	},
	{
		name: "印度",
		flag: "🇮🇳",
	},
	{
		name: "印度尼西亚",
		flag: "🇮🇩",
	},
	{
		name: "伊朗伊斯兰共和国",
		flag: "🇮🇷",
	},
	{
		name: "伊拉克",
		flag: "🇮🇶",
	},
	{
		name: "爱尔兰",
		flag: "🇮🇪",
	},
	{
		name: "马恩岛",
		flag: "🇮🇲",
	},
	{
		name: "以色列",
		flag: "🇮🇱",
	},
	{
		name: "意大利",
		flag: "🇮🇹",
	},
	{
		name: "牙买加",
		flag: "🇯🇲",
	},
	{
		name: "日本",
		flag: "🇯🇵",
	},
	{
		name: "泽西岛",
		flag: "🇯🇪",
	},
	{
		name: "约旦",
		flag: "🇯🇴",
	},
	{
		name: "哈萨克斯坦",
		flag: "🇰🇿",
	},
	{
		name: "肯尼亚",
		flag: "🇰🇪",
	},
	{
		name: "基里巴斯",
		flag: "🇰🇮",
	},
	{
		name: "朝鲜",
		flag: "🇰🇵",
	},
	{
		name: "韩国",
		flag: "🇰🇷",
	},
	{
		name: "科威特",
		flag: "🇰🇼",
	},
	{
		name: "吉尔吉斯斯坦",
		flag: "🇰🇬",
	},
	{
		name: "老挝人民民主共和国",
		flag: "🇱🇦",
	},
	{
		name: "拉脱维亚",
		flag: "🇱🇻",
	},
	{
		name: "黎巴嫩",
		flag: "🇱🇧",
	},
	{
		name: "莱索托",
		flag: "🇱🇸",
	},
	{
		name: "利比里亚",
		flag: "🇱🇷",
	},
	{
		name: "利比亚",
		flag: "🇱🇾",
	},
	{
		name: "列支敦士登",
		flag: "🇱🇮",
	},
	{
		name: "立陶宛",
		flag: "🇱🇹",
	},
	{
		name: "卢森堡",
		flag: "🇱🇺",
	},
	{
		name: "澳门",
		flag: "🇲🇴",
	},
	{
		name: "前南斯拉夫马其顿共和国",
		flag: "🇲🇰",
	},
	{
		name: "马达加斯加",
		flag: "🇲🇬",
	},
	{
		name: "马拉维",
		flag: "🇲🇼",
	},
	{
		name: "马来西亚",
		flag: "🇲🇾",
	},
	{
		name: "马尔代夫",
		flag: "🇲🇻",
	},
	{
		name: "马里",
		flag: "🇲🇱",
	},
	{
		name: "马耳他",
		flag: "🇲🇹",
	},
	{
		name: "马绍尔群岛",
		flag: "🇲🇭",
	},
	{
		name: "马提尼克",
		flag: "🇲🇶",
	},
	{
		name: "毛里塔尼亚",
		flag: "🇲🇷",
	},
	{
		name: "毛里求斯",
		flag: "🇲🇺",
	},
	{
		name: "马约特",
		flag: "🇾🇹",
	},
	{
		name: "墨西哥",
		flag: "🇲🇽",
	},
	{
		name: "密克罗尼西亚联邦",
		flag: "🇫🇲",
	},
	{
		name: "摩尔多瓦共和国",
		flag: "🇲🇩",
	},
	{
		name: "摩纳哥",
		flag: "🇲🇨",
	},
	{
		name: "蒙古",
		flag: "🇲🇳",
	},
	{
		name: "黑山",
		flag: "🇲🇪",
	},
	{
		name: "蒙特塞拉特",
		flag: "🇲🇸",
	},
	{
		name: "摩洛哥",
		flag: "🇲🇦",
	},
	{
		name: "莫桑比克",
		flag: "🇲🇿",
	},
	{
		name: "缅甸",
		flag: "🇲🇲",
	},
	{
		name: "纳米比亚",
		flag: "🇳🇦",
	},
	{
		name: "瑙鲁",
		flag: "🇳🇷",
	},
	{
		name: "尼泊尔",
		flag: "🇳🇵",
	},
	{
		name: "荷兰",
		flag: "🇳🇱",
	},
	{
		name: "新喀里多尼亚",
		flag: "🇳🇨",
	},
	{
		name: "新西兰",
		flag: "🇳🇿",
	},
	{
		name: "尼加拉瓜",
		flag: "🇳🇮",
	},
	{
		name: "尼日尔",
		flag: "🇳🇪",
	},
	{
		name: "尼日利亚",
		flag: "🇳🇬",
	},
	{
		name: "纽埃",
		flag: "🇳🇺",
	},
	{
		name: "诺福克岛",
		flag: "🇳🇫",
	},
	{
		name: "北马里亚纳群岛",
		flag: "🇲🇵",
	},
	{
		name: "挪威",
		flag: "🇳🇴",
	},
	{
		name: "阿曼",
		flag: "🇴🇲",
	},
	{
		name: "巴基斯坦",
		flag: "🇵🇰",
	},
	{
		name: "帕劳",
		flag: "🇵🇼",
	},
	{
		name: "巴勒斯坦国",
		flag: "🇵🇸",
	},
	{
		name: "巴拿马",
		flag: "🇵🇦",
	},
	{
		name: "巴布亚新几内亚",
		flag: "🇵🇬",
	},
	{
		name: "巴拉圭",
		flag: "🇵🇾",
	},
	{
		name: "秘鲁",
		flag: "🇵🇪",
	},
	{
		name: "菲律宾",
		flag: "🇵🇭",
	},
	{
		name: "皮特凯恩",
		flag: "🇵🇳",
	},
	{
		name: "波兰",
		flag: "🇵🇱",
	},
	{
		name: "葡萄牙",
		flag: "🇵🇹",
	},
	{
		name: "波多黎各",
		flag: "🇵🇷",
	},
	{
		name: "卡塔尔",
		flag: "🇶🇦",
	},
	{
		name: "留尼汪",
		flag: "🇷🇪",
	},
	{
		name: "罗马尼亚",
		flag: "🇷🇴",
	},
	{
		name: "俄罗斯联邦",
		flag: "🇷🇺",
	},
	{
		name: "卢旺达",
		flag: "🇷🇼",
	},
	{
		name: "圣巴泰勒米",
		flag: "🇧🇱",
	},
	{
		name: "圣赫勒拿、阿森松和特里斯坦达库尼亚",
		flag: "🇸🇭",
	},
	{
		name: "圣基茨和尼维斯",
		flag: "🇰🇳",
	},
	{
		name: "圣卢西亚",
		flag: "🇱🇨",
	},
	{
		name: "法属圣马丁",
		flag: "🇲🇫",
	},
	{
		name: "圣皮埃尔和密克隆",
		flag: "🇵🇲",
	},
	{
		name: "圣文森特和格林纳丁斯",
		flag: "🇻🇨",
	},
	{
		name: "萨摩亚",
		flag: "🇼🇸",
	},
	{
		name: "圣马力诺",
		flag: "🇸🇲",
	},
	{
		name: "圣多美和普林西比",
		flag: "🇸🇹",
	},
	{
		name: "沙特阿拉伯",
		flag: "🇸🇦",
	},
	{
		name: "塞内加尔",
		flag: "🇸🇳",
	},
	{
		name: "塞尔维亚",
		flag: "🇷🇸",
	},
	{
		name: "塞舌尔",
		flag: "🇸🇨",
	},
	{
		name: "塞拉利昂",
		flag: "🇸🇱",
	},
	{
		name: "新加坡",
		flag: "🇸🇬",
	},
	{
		name: "荷属圣马丁",
		flag: "🇸🇽",
	},
	{
		name: "斯洛伐克",
		flag: "🇸🇰",
	},
	{
		name: "斯洛文尼亚",
		flag: "🇸🇮",
	},
	{
		name: "所罗门群岛",
		flag: "🇸🇧",
	},
	{
		name: "索马里",
		flag: "🇸🇴",
	},
	{
		name: "南非",
		flag: "🇿🇦",
	},
	{
		name: "南乔治亚和南桑威奇群岛",
		flag: "🇬🇸",
	},
	{
		name: "南苏丹",
		flag: "🇸🇸",
	},
	{
		name: "西班牙",
		flag: "🇪🇸",
	},
	{
		name: "斯里兰卡",
		flag: "🇱🇰",
	},
	{
		name: "苏丹",
		flag: "🇸🇩",
	},
	{
		name: "苏里南",
		flag: "🇸🇷",
	},
	{
		name: "斯瓦尔巴和扬马延",
		flag: "🇸🇯",
	},
	{
		name: "斯威士兰",
		flag: "🇸🇿",
	},
	{
		name: "瑞典",
		flag: "🇸🇪",
	},
	{
		name: "瑞士",
		flag: "🇨🇭",
	},
	{
		name: "阿拉伯叙利亚共和国",
		flag: "🇸🇾",
	},
	{
		name: "中国台湾省",
		flag: "🇹🇼",
	},
	{
		name: "塔吉克斯坦",
		flag: "🇹🇯",
	},
	{
		name: "坦桑尼亚联合共和国",
		flag: "🇹🇿",
	},
	{
		name: "泰国",
		flag: "🇹🇭",
	},
	{
		name: "东帝汶",
		flag: "🇹🇱",
	},
	{
		name: "多哥",
		flag: "🇹🇬",
	},
	{
		name: "托克劳",
		flag: "🇹🇰",
	},
	{
		name: "汤加",
		flag: "🇹🇴",
	},
	{
		name: "特立尼达和多巴哥",
		flag: "🇹🇹",
	},
	{
		name: "突尼斯",
		flag: "🇹🇳",
	},
	{
		name: "土耳其",
		flag: "🇹🇷",
	},
	{
		name: "土库曼斯坦",
		flag: "🇹🇲",
	},
	{
		name: "特克斯和凯科斯群岛",
		flag: "🇹🇨",
	},
	{
		name: "图瓦卢",
		flag: "🇹🇻",
	},
	{
		name: "乌干达",
		flag: "🇺🇬",
	},
	{
		name: "乌克兰",
		flag: "🇺🇦",
	},
	{
		name: "阿拉伯联合酋长国",
		flag: "🇦🇪",
	},
	{
		name: "英国",
		flag: "🇬🇧",
	},
	{
		name: "美国",
		flag: "🇺🇸",
	},
	{
		name: "美国本土外小岛屿",
		flag: "🇺🇲",
	},
	{
		name: "乌拉圭",
		flag: "🇺🇾",
	},
	{
		name: "乌兹别克斯坦",
		flag: "🇺🇿",
	},
	{
		name: "瓦努阿图",
		flag: "🇻🇺",
	},
	{
		name: "委内瑞拉玻利瓦尔共和国",
		flag: "🇻🇪",
	},
	{
		name: "越南",
		flag: "🇻🇳",
	},
	{
		name: "英属维尔京群岛",
		flag: "🇻🇬",
	},
	{
		name: "美属维尔京群岛",
		flag: "🇻🇮",
	},
	{
		name: "瓦利斯和富图纳",
		flag: "🇼🇫",
	},
	{
		name: "西撒哈拉",
		flag: "🇪🇭",
	},
	{
		name: "也门",
		flag: "🇾🇪",
	},
	{
		name: "赞比亚",
		flag: "🇿🇲",
	},
	{
		name: "津巴布韦",
		flag: "🇿🇼",
	},
];
