// Code generated by typegen/main.go. DO NOT EDIT.

import type { RBACAction, RBACResource } from "./typesGenerated";

// RBACResourceActions maps RBAC resources to their possible actions.
// Descriptions are included to document the purpose of each action.
// Source is in 'coderd/rbac/policy/policy.go'.
export const RBACResourceActions: Partial<
	Record<RBACResource, Partial<Record<RBACAction, string>>>
> = {
	ai_gateway_key: {
		create: "创建 AI Gateway 密钥",
		delete: "删除 AI Gateway 密钥",
		read: "读取 AI Gateway 密钥",
	},
	ai_model_price: {
		read: "读取 AI 模型价格",
		update: "更新 AI 模型价格",
	},
	ai_provider: {
		create: "创建 AI 提供商",
		delete: "删除 AI 提供商",
		read: "读取 AI 提供商配置",
		update: "更新 AI 提供商",
	},
	ai_seat: {
		create: "记录 AI 座位使用情况",
		read: "读取 AI 座位状态",
	},
	aibridge_interception: {
		create: "创建 aibridge 拦截及相关记录",
		read: "读取 aibridge 拦截及相关记录",
		update: "更新 aibridge 拦截及相关记录",
	},
	api_key: {
		create: "创建 API 密钥",
		delete: "删除 API 密钥",
		read: "读取 API 密钥详情（不存储密钥）",
		update: "更新 API 密钥，例如过期时间",
	},
	assign_org_role: {
		assign: "分配组织范围内的角色",
		create: "在组织内创建/删除自定义角色",
		delete: "删除组织内的角色",
		read: "查看组织内可分配的角色",
		unassign: "取消分配组织范围内的角色",
		update: "编辑组织内的自定义角色",
	},
	assign_role: {
		assign: "分配用户角色",
		read: "查看可分配的角色",
		unassign: "取消分配用户角色",
	},
	audit_log: {
		create: "创建新的审计日志条目",
		read: "读取审计日志",
	},
	boundary_log: {
		create: "创建边界日志记录",
		delete: "删除边界日志",
		read: "读取边界日志和会话元数据",
	},
	boundary_usage: {
		delete: "删除边界使用统计",
		read: "读取边界使用统计",
		update: "插入或更新边界使用统计",
	},
	chat: {
		create: "创建新的聊天",
		delete: "删除聊天",
		read: "读取聊天消息和元数据",
		share: "与其他用户或组共享聊天",
		update: "更新聊天标题或设置",
	},
	connection_log: {
		read: "读取连接日志",
		update: "插入或更新连接日志条目",
	},
	crypto_key: {
		create: "创建加密密钥",
		delete: "删除加密密钥",
		read: "读取加密密钥",
		update: "更新加密密钥",
	},
	debug_info: {
		read: "访问调试路由",
	},
	deployment_config: {
		read: "读取部署配置",
		update: "更新健康信息",
	},
	deployment_stats: {
		read: "读取部署统计",
	},
	file: {
		create: "创建文件",
		read: "读取文件",
	},
	group: {
		create: "创建用户组",
		delete: "删除用户组",
		read: "读取用户组",
		update: "更新用户组",
	},
	group_member: {
		read: "读取组成员",
	},
	idpsync_settings: {
		read: "读取 IdP 同步设置",
		update: "更新 IdP 同步设置",
	},
	inbox_notification: {
		create: "创建收件箱通知",
		read: "读取收件箱通知",
		update: "更新收件箱通知",
	},
	license: {
		create: "创建许可证",
		delete: "删除许可证",
		read: "读取许可证",
	},
	notification_message: {
		create: "创建通知消息",
		delete: "删除通知消息",
		read: "读取通知消息",
		update: "更新通知消息",
	},
	notification_preference: {
		read: "读取通知偏好设置",
		update: "更新通知偏好设置",
	},
	notification_template: {
		read: "读取通知模板",
		update: "更新通知模板",
	},
	oauth2_app: {
		create: "创建 OAuth2 应用",
		delete: "删除 OAuth2 应用",
		read: "读取 OAuth2 应用",
		update: "更新 OAuth2 应用的属性",
	},
	oauth2_app_code_token: {
		create: "创建 OAuth2 应用代码令牌",
		delete: "删除 OAuth2 应用代码令牌",
		read: "读取 OAuth2 应用代码令牌",
	},
	oauth2_app_secret: {
		create: "创建 OAuth2 应用密钥",
		delete: "删除 OAuth2 应用密钥",
		read: "读取 OAuth2 应用密钥",
		update: "更新 OAuth2 应用密钥",
	},
	organization: {
		create: "创建组织",
		delete: "删除组织",
		read: "读取组织",
		update: "更新组织",
	},
	organization_member: {
		create: "创建组织成员",
		delete: "删除成员",
		read: "读取成员",
		update: "更新组织成员",
	},
	prebuilt_workspace: {
		delete: "删除预构建工作区",
		update: "更新预构建工作区设置",
	},
	provisioner_daemon: {
		create: "创建配置程序守护进程/密钥",
		delete: "删除配置程序守护进程/密钥",
		read: "读取配置程序守护进程",
		update: "更新配置程序守护进程",
	},
	provisioner_jobs: {
		create: "创建配置程序任务",
		read: "读取配置程序任务",
		update: "更新配置程序任务",
	},
	replicas: {
		read: "读取副本",
	},
	system: {
		create: "创建系统资源",
		delete: "删除系统资源",
		read: "查看系统资源",
		update: "更新系统资源",
	},
	tailnet_coordinator: {
		create: "创建 Tailnet 协调器",
		delete: "删除 Tailnet 协调器",
		read: "查看 Tailnet 协调器信息",
		update: "更新 Tailnet 协调器",
	},
	task: {
		create: "创建新任务",
		delete: "删除任务",
		read: "读取任务数据或输出以便在 UI 或 CLI 上查看",
		update: "编辑任务设置或向现有任务发送输入",
	},
	template: {
		create: "创建模板",
		delete: "删除模板",
		read: "读取模板",
		update: "更新模板",
		use: "使用模板初次创建工作区，之后由工作区生命周期权限接管",
		view_insights: "查看洞察",
	},
	usage_event: {
		create: "创建使用事件",
		read: "读取使用事件",
		update: "更新使用事件",
	},
	user: {
		create: "创建新用户",
		delete: "删除现有用户",
		read: "读取用户数据",
		read_personal: "读取个人用户数据，如用户设置和认证链接",
		update: "更新现有用户",
		update_personal: "更新个人数据",
	},
	user_secret: {
		create: "创建用户密钥",
		delete: "删除用户密钥",
		read: "读取用户密钥元数据和值",
		update: "更新用户密钥元数据和值",
	},
	user_skill: {
		create: "创建用户技能",
		delete: "删除用户技能",
		read: "读取用户技能元数据和内容",
		update: "更新用户技能元数据和内容",
	},
	webpush_subscription: {
		create: "创建 WebPush 订阅",
		delete: "删除 WebPush 订阅",
		read: "读取 WebPush 订阅",
	},
	workspace: {
		application_connect: "通过浏览器连接到工作区应用",
		create: "创建新工作区",
		create_agent: "创建新的工作区代理",
		delete: "删除工作区",
		delete_agent: "删除现有的工作区代理",
		read: "读取工作区数据以在 UI 上查看",
		share: "与其他用户或组共享工作区",
		ssh: "通过 SSH 连接到给定工作区",
		start: "允许启动工作区",
		stop: "允许停止工作区",
		update: "编辑工作区设置（调度、权限、参数）",
		update_agent: "更新现有的工作区代理",
	},
	workspace_agent_devcontainers: {
		create: "创建工作区代理开发容器",
	},
	workspace_agent_resource_monitor: {
		create: "创建工作区代理资源监控",
		read: "读取工作区代理资源监控",
		update: "更新工作区代理资源监控",
	},
	workspace_dormant: {
		application_connect: "通过浏览器连接到工作区应用",
		create: "创建新工作区",
		create_agent: "创建新的工作区代理",
		delete: "删除工作区",
		delete_agent: "删除现有的工作区代理",
		read: "读取工作区数据以在 UI 上查看",
		share: "与其他用户或组共享工作区",
		ssh: "通过 SSH 连接到给定工作区",
		start: "允许启动工作区",
		stop: "允许停止工作区",
		update: "编辑工作区设置（调度、权限、参数）",
		update_agent: "更新现有的工作区代理",
	},
	workspace_proxy: {
		create: "创建工作区代理",
		delete: "删除工作区代理",
		read: "读取并使用工作区代理",
		update: "更新工作区代理",
	},
};
